### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by ganpaper** [duongvinh/RR-HLFSR_NTIRE2023_LFSR#2]
Hi! Thanks for your code! I am  interested in your work.
When I tried to train the model, I encountered the following problems:

Total Params: 28988919.00

PARAMETER ...
Namespace(angRes_in=5, angRes_out=5, batch_size=1, channels=64, crop_test_method=3, data_name='ALL', decay_rate=0, device='cuda:0', epoch=10, gamma=0.5, local_rank=0, lr=0.0002, minibatch_for_test=16, model_name='RR_HLFSR', n_blocks=15, n_groups=10, n_steps=15, num_workers=2, parallel=False, patch_size_for_test=32, path_for_test='./data_for_test/', path_for_train='./data_for_training/', path_log='./log/', path_pre_pth='./pretrained_model/RR_HLFSR_4xSR_5x5.pth.tar', precision='single', save_path='../Results/', scale_factor=4, self_ensemble=True, step_validation=15, stride_for_test=16, task='SR', test_NTIRE2023_LFSR=0, use_pre_ckpt=True)

Start training...

Epoch 1 /10:
100%|█████████████████████████| 11200/11200 [3:04:09<00:00,  1.01it/s]
The 1th Train, loss is: 0.02094, psnr is 31.27283, ssim is 0.90605
Saving the epoch_01 model at log/SR_5x5_4x/ALL/RR_HLFSR/checkpoints/RR_HLFSR_5x5_4x_epoch_01_model.pth
100%|█████████████████████████████████| 10/10 [12:54<00:00, 77.47s/it]
Traceback (most recent call last):
  File "train.py", line 463, in <module>
    main(args)
  File "train.py", line 148, in main
    psnr_iter_test, ssim_iter_test, LF_name = test(test_loader, device, net, save_dir)
ValueError: too many values to unpack (expected 3)

**Comment by duongvinh** [comment]
you can remove the "total_time" in line 457 in train.py file, then it will be OK. I have cleaned and updated the code. Thank you!

**Comment by ganpaper** [comment]
Thanks!
